phd_centre/urls.py
from django.contrib import admin
from django.urls import path, include

#from phd_centre import settings
#from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('phdc_app.urls')),
	
	#path('accounts/', include('django.contrib.auth.urls')),
] # + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

phdc_app/urls.py
from django.urls import path, include
from django.conf.urls.static import static

from phd_centre import settings 
from . import views


app_name='phdc_app'
urlpatterns=[
	# ===== Домашня сторінка =====  
	path('', views.home, name='home'),
    
	# ===== Реєстрація студента ===== 
	path('register', views.register, name='register'),
    
	# ===== Вхід в систему ===== 
	path('login_page', views.login_page, name='login_page'),
    # ===== Вихід із системи ===== 
	path('logout', views.logout_user, name='logout'),
	
	# ===== Панель керування ===== 
	path('home_admin', views.home_admin, name='home_admin'),

	# ===== Викладачі ===== 
	path('teachers', views.teachers, name='teachers'),
	path('teachers/', views.teacher_list, name='teacher_list'),
	path('teachers/add', views.add_teacher, name='add_teacher'),
	path('teachers/<int:id>/edit', views.edit_teacher, name='edit_teacher'), 
	path('teachers/<int:id>/delete', views.delete_teacher, name='delete_teacher'),

	# ===== Групи ===== 
	path('study_groups', views.study_groups, name='study_groups'),
	path('study_groups/', views.study_group_list, name='study_group_list'),
	path('study_groups/add', views.add_study_group, name='add_study_group'),
	path('study_groups/<int:id>/edit', views.edit_study_group, name='edit_study_group'),
	path('study_groups/<int:id>/delete', views.delete_study_group, name='delete_study_group'),
	path('study_group/<str:id>/', views.study_group, name='study_group'),

	# ===== Аспіранти ===== 
	path('students', views.students, name='students'),
	path('student_profile/<str:id>/', views.student_profile, name='student_profile'), 
	path('student_profile/<str:id>/edit_student/', views.edit_student, name='edit_student'),
	path('student_profile_nav/', views.student_profile_nav, name='student_profile_nav'),
    path('delete_student/<str:id>/', views.delete_student, name='delete_student'), 
    
	# ===== Навчальний план ===== 
	path('student/<str:id>/educ_plans', views.educ_plans, name='educ_plans'),
	path('student/<str:id>/educ_plans/', views.educ_plan_list, name='educ_plan_list'),
	path('educ_plans/<str:id>/add/', views.add_educ_plan, name='add_educ_plan'),
	path('educ_plans/<str:id>/<student_id>/edit/', views.edit_educ_plan, name='edit_educ_plan'),
	path('educ_plans/<str:id>/delete/', views.delete_educ_plan, name='delete_educ_plan'),
    
	# ===== План наукової роботи ===== 
	path('student/<int:id>/research_plans', views.research_plans, name='research_plans'),
	path('student/<int:id>/research_plans/', views.research_plan_list, name='research_plan_list'),
	path('research_plans/<int:id>/research_plans/add', views.add_research_plan, name='add_research_plan'),
	path('research_plans/<int:id>/research_plans/edit', views.edit_research_plan, name='edit_research_plan'),
	path('research_plans/<int:id>/research_plans/delete', views.delete_research_plan, name='delete_research_plan'),
	path('research_plans/<int:id>/show_research_plan', views.show_research_plan, name='show_research_plan'),
    path('research_plans/<int:id>/impl_research_plan', views.impl_research_plan, name='impl_research_plan'),
    
	# ===== Дисертація ===== 
	path('student/<str:id>/dissertation/', views.dissertation, name='dissertation'),
	path('student/<str:id>/add_dissertation/', views.add_dissertation, name='add_dissertation'),
    path('disseration/<str:id>/<str:state>/edit_dissertation/', views.edit_dissertation, name='edit_dissertation'),
	path('disseration/<str:id>/delete_dissertation/', views.delete_dissertation, name='delete_dissertation'),
    path('dissertation/download_file/<int:id>/', views.download_file, name='download_file'),
    path('dissertation/<str:id>/states/', views.states, name='states'),
    
	# ===== Протоколи ===== 
	path('student/<str:id>/protocols', views.protocols, name='protocols'),
	path('student/<str:id>/protocols/', views.protocol_list, name='protocol_list'),
	path('protocols/<str:id>/add/', views.add_protocol, name='add_protocol'),
	path('protocols/<str:id>/<student_id>/edit/', views.edit_protocol, name='edit_protocol'),
	path('protocols/<str:id>/delete/', views.delete_protocol, name='delete_protocol'),
    

	# ===== НАКАЗИ ===== 

	path('student/<str:id>/orders', views.orders, name='orders'),
	path('student/<str:id>/orders/', views.order_list, name='order_list'),
	path('orders/<str:id>/add/', views.add_order, name='add_order'),
	path('orders/<str:id>/<student_id>/edit/', views.edit_order, name='edit_order'),
	path('orders/<str:id>/delete/', views.delete_order, name='delete_order'),
    
	# ===== ЗВІТИ ===== 
 	path('student/<str:id>/reports', views.reports, name='reports'),
	path('student/<str:id>/reports/', views.report_list, name='report_list'),
	path('reports/<str:id>/add/', views.add_report, name='add_report'),
	path('reports/<str:id>/<student_id>/edit/', views.edit_report, name='edit_report'),
	path('reports/<str:id>/delete/', views.delete_report, name='delete_report'),   
	path('download_report/<int:id>/', views.download_report, name='download_report'),
    
	# ===== Кафедри ===== 
	path('departments', views.departments, name='departments'),
	path('departments/', views.department_list, name='department_list'),
	path('departments/add', views.add_department, name='add_department'),
	path('departments/<int:id>/delete', views.delete_department, name='delete_department'),
    
	# ===== Видання ===== 
	path('editions', views.editions, name='editions'),
	path('editions/', views.edition_list, name='edition_list'),
	path('editions/add', views.add_edition, name='add_edition'),
	path('editions/<int:id>/edit', views.edit_edition, name='edit_edition'),
	path('editions/<int:id>/delete', views.delete_edition, name='delete_edition'),

	# ===== Спеціальності видання ===== 
	path('editions/<int:id>/edition_specs', views.edition_specs, name='edition_specs'),
	path('editions/<int:id>/edition_specs/', views.edition_spec_list, name='edition_spec_list'),
	path('editions/<int:id>/edition_specs/add', views.add_edition_spec, name='add_edition_spec'),
	path('editions/<int:id>/<int:edition_id>/edition_specs/delete', views.delete_edition_spec, name='delete_edition_spec'),

	# ===== Спеціальності ===== 
	path('specialties', views.specialties, name='specialties'),
	path('specialties/', views.specialty_list, name='specialty_list'),
	path('specialties/add', views.add_specialty, name='add_specialty'),
	path('specialties/<str:id>/edit', views.edit_specialty, name='edit_specialty'),
	path('specialties/<int:id>/delete', views.delete_specialty, name='delete_specialty'),

	# ===== Типи публікацій ===== 
	path('pub_types', views.pub_types, name='pub_types'),
	path('pub_types/', views.pub_type_list, name='pub_type_list'),
	path('pub_types/add', views.add_pub_type, name='add_pub_type'),
	path('pub_types/<int:id>/delete', views.delete_pub_type, name='delete_pub_type'),

	# ===== Публікації ===== 
	path('publications/<int:id>', views.publications, name='publications'),
	path('publications/<int:id>/', views.publication_list, name='publication_list'),
	path('publications/<int:student_id>/add', views.add_publication, name='add_publication'),
	path('publications/<int:publication_id>/delete', views.delete_publication, name='delete_publication'),

	path('publication/<str:id>/', views.publication, name='publication'),
	path('publication/<str:id>/edit_publication/', views.edit_publication, name='edit_publication'),
    
	# ===== Автори публікації ===== 
	path('authors/<int:id>', views.authors, name='authors'),
    path('authors/<int:id>/', views.author_list, name='author_list'),
    path('authors/<int:id>/add_authors', views.add_authors, name='add_authors'),
    path('authors/<int:id>/delete_author ', views.delete_author, name='delete_author'),

	# ===== Дедлайни ===== 
	path('deadlines', views.deadlines, name='deadlines'),
	path('deadlines/', views.deadline_list, name='deadline_list'),
	path('add_deadline_submission/<int:id>', views.add_deadline_submission, name='add_deadline_submission'),
    path('delete_deadline_submission/<int:id>', views.delete_deadline_submission, name='delete_deadline_submission'),
	path('deadlines/add', views.add_deadline, name='add_deadline'),
	path('deadlines/<int:id>/edit', views.edit_deadline, name='edit_deadline'),
	path('deadlines/<int:id>/delete', views.delete_deadline, name='delete_deadline'),
	path('deadlines/<int:id>/show_info', views.show_deadline_info, name='show_deadline_info'),
	path('deadline_submissions/<int:id>', views.deadline_submissions, name='deadline_submissions'),
	path('deadline_submissions/<int:id>/', views.deadline_submission_list, name='deadline_submission_list'),
	path('deadline_submissions/<int:id>/<int:deadline_id>/approve_submission', views.approve_submission, name='approve_submission'),
	path('deadline_submissions/<int:id>/<int:deadline_id>/decline_submission', views.decline_submission, name='decline_submission'),

	# ===== Список перевірки ===== 
	path('blacklists', views.blacklists, name='blacklists'),
	path('blacklists_cats/<str:category>', views.blacklists_cats, name='blacklists_cats'),
	path('blacklist_list/<str:category>/', views.blacklist_list, name='blacklist_list'),
    path('student/<str:id>/add_student_to_bl/', views.add_student_to_bl, name='add_student_to_bl'),
	path('blacklist_list/<int:id>/delete_bl_entry', views.delete_bl_entry, name='delete_bl_entry'),
    path('show_bl_entry_info/<int:id>', views.show_bl_entry_info, name='show_bl_entry_info'),
    
    
	# ===== Сповіщення ===== 
	path('notifications', views.notifications, name='notifications'),
	path('show_notifications/', views.show_notifications, name='show_notifications'),
    path('show_notifications', views.show_notifications, name='show_notifications'),
    path('show_student_notifications/', views.show_student_notifications, name='show_student_notifications'),
    
	# ===== Адмін ===== 
    path('admin_settings', views.admin_settings, name='admin_settings'),
    path('registration_status_toggle', views.registration_status_toggle, name='registration_status_toggle'),   

phdc_app/templates/blacklist_delete_modal.html
<div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><i class="ri-delete-bin-5-line"></i>&nbsp;Видалення</h5>
      </div>
      <div class="modal-body">
        <p class="text-center" style="font-size: 1.2rem; font-weight: 400; color:#FF6961;">Видалити аспіранта зі списку перевірки?</p>
      </div>
      <div class="modal-footer">
        <form method="post" hx-post="{% url 'phdc_app:delete_bl_entry' id=id %}" hx-trigger="click" hx-swap="none">
          {% csrf_token %}
          <button type="submit" class="btn btn-danger" id="modal-logout-btn">Видалити</button>
        </form>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" id="modal-close-btn">Закрити</button>
      </div>
    </div>
  </div>

phdc_app/templates/deadline_edit_modal.html
{% load crispy_forms_tags %}

<form method="post" hx-post="{% url 'phdc_app:edit_deadline' id=id %}" hx-trigger="submit" hx-swap="none" hx-on="htmx:afterRequest: window.location.reload()" class="modal-content">
  {% csrf_token %}
  <div class="modal-header"> 
    <h5 class="modal-title"><i class="ri-pencil-line" style="color: #92e3a9;"></i> Редагування дедлайну</h5>
  </div>
  <div class="modal-body">
    {% csrf_token %}
    {{ form|crispy }}
  </div>
  <div class="modal-footer">
    <button type="submit" id="modal-save-btn">Зберегти</button>
    <button type="button" data-bs-dismiss="modal" id="modal-close-btn">Закрити</button>
  </div>
</form>

phdc_app/templates/deadlines.html
{% extends 'home_admin.html' %}


{% block base-title %} PHDCENTRE: Дедлайни {% endblock base-title %}

{% block homea-cards-list %} container mt-3 deadl-main-section {% endblock homea-cards-list %}

{% block homea-section-title %}
<i class="ri-timer-line"></i>&nbsp;Дедлайни
{% endblock homea-section-title %}

{% block homea-cards-list-content %}
{% if group != 'phdstudents' %}
{% block add-deadl %}
<div class="deadlines-top" style="position: relative; top: -2rem; left: 34.5rem;">
  <a href="{% url 'phdc_app:add_deadline' %}" data-bs-backdrop="static" class="btn btn-outline-secondary main-btn add-btn" id="deadl-add-btn">
    <i class="ri-add-circle-line"></i> Створити дедлайн
  </a>
</div>
{% endblock add-deadl %}
{% endif %}

<div class="deadl-cards">
  {% block deadl-cards %}
  {% for data in deadlines %}
  <div class="deadl-card">
    <div class="deadl-card-img">
      <div class="deadl-card-imgbox">
        {% if data.date > currdate %}
        <img src="/static/images/deadline.png">
        {% else %}
        <img src="/static/images/deadlinenoactive.png">
        {% endif %}
      </div>
    </div>
    <div class="deadl-card-content">
      <h4>{{ data.category }}</h4>
      <button hx-get="{% url 'phdc_app:show_deadline_info' id=data.id %}" hx-target="#dialog" data-bs-backdrop="static" id="table-btn" class="deadl-edit" type="button">
        <i class="ri-file-copy-2-line"></i>
      </button>
      {% if group != 'phdstudents' %}
      <a href="{% url 'phdc_app:deadline_submissions' id=data.id %}" class="btn btn-outline-secondary" id="deadl-view">
        <i class="ri-eye-line"></i>
      </a>
      <button hx-get="{% url 'phdc_app:edit_deadline' id=data.id %}" hx-target="#dialog" data-bs-backdrop="static" id="table-btn" class="deadl-edit" type="button">
        <i class="ri-pencil-line"></i>
      </button>
      <button hx-get="{% url 'phdc_app:delete_deadline' id=data.id %}" hx-target="#dialog" data-bs-backdrop="static" id="table-btn" class="deadl-del" type="button">
        <i class="ri-delete-bin-line"></i>
      </button>
      {% endif %}
      {% if group == 'phdstudents' %}
        <button hx-get="{% url 'phdc_app:add_deadline_submission' id=data.id %}" hx-target="#dialog" data-bs-backdrop="static" id="table-btn" class="deadl-edit" type="button">
          <i class="ri-add-line"></i>
        </button>
        <button hx-get="{% url 'phdc_app:delete_deadline_submission' id=data.id %}" hx-target="#dialog" data-bs-backdrop="static" id="table-btn" class="deadl-del" type="button">
          <i class="ri-subtract-line"></i>
        </button>
        
      {% endif %}
    </div>
  </div>
  {% empty %}
  <div><strong>Записи відсутні</strong></div>
  {% endfor %}
  {% endblock deadl-cards %}
</div>
{% endblock homea-cards-list-content %}

phdc_app/templates/department_list.html
{% for data in departments %}
<tr>
  <td>{{ data.name }}</td>
  <td>{{ data.abbreviation }}</td>
  <td class="s-table-btns">
    <button hx-get="{% url 'phdc_app:delete_department' id=data.id %}" hx-target="#dialog" data-bs-backdrop="static" class="btn btn-outline-secondary btn-sm text-light" id="table-delete-btn">
      <i class="ri-delete-bin-line"></i>
    </button>
  </td>
  {% empty %}
  <td colspan="2" class="s-table-empty-rcrd"><strong>Записи відсутні</strong></td>
</tr>
{% endfor %}

phdc_app/templates/home_admin.html
{% extends 'base.html' %}


{% block base-title %} PHDCENTRE: Панель керування {% endblock base-title %}

{% block base-nav-bg %} homea-nav-bg {% endblock base-nav-bg %}
{% block base-nav-content %}
<div class="homea-navbar">
	<i class="ri-menu-line sidebar-menu"></i>
	<span class="phdclogo">
		<a href="#">
			<i class="ri-graduation-cap-line" style="color: #92e3a9; font-size: 30px;"></i>&nbsp;PHDCENTRE
		</a>
	</span>
	
	<div class="homea-nav-menu">
		<div class="homea-nav-logo-toggle">
			<span class="phdclogo">
				<a href="#" id="phdclogo-siderbar">
					<i class="ri-graduation-cap-line" style="color: #92e3a9; font-size: 30px;"></i>&nbsp;PHDCENTRE
				</a>
			</span>
		</div>
		<br class="homea-sidebar-seprtr">
		<hr class="homea-sidebar-seprtr">

		{% if group != 'phdstudents' %}
		<ul class="homea-nav-ul">
			<li>
				<a href="{% url 'phdc_app:home_admin' %}" class="btn">
					<i class="ri-tools-line" id="homea-controlp-icon"></i>&nbsp;<span id="homea-controlp-text">Панель&nbsp;керування</span> 
				</a>
			</li> 
			<li>
				<button hx-get="{% url 'phdc_app:send_email' %}" hx-target="#dialog" data-bs-backdrop="static" class="btn">
					<i class="ri-chat-3-line" id="homea-msg-icon"></i>&nbsp;<span id="homea-msg-text">Повідомлення</span>
				</button>
			</li>
			<li>
				<a href="{% url 'phdc_app:deadlines' %}" class="btn">
					<i class="ri-timer-line" id="homea-deadline-icon"></i>&nbsp;<span id="homea-deadline-text">Дедлайни</span> 
				</a>
			</li>
			<li>
				<a href="{% url 'phdc_app:blacklists' %}" class="btn"> 
					<i class="ri-user-search-line" id="homea-blacklist-icon"></i>&nbsp;<span id="homea-blacklist-text">Список&nbsp;перевірки</span> 
				</a>
			</li>
			<li>
				<button hx-get="{% url 'phdc_app:admin_settings' %}" hx-target="#dialog" data-bs-backdrop="static" class="btn">
					<i class="ri-user-settings-line" id="homea-settings-icon"></i>&nbsp;<span id="homea-settings-text">Налаштування</span>
				</button>
			</li>
		</ul>
		{% endif %}

		{% if group == 'phdstudents' %}
		<ul class="homea-nav-ul" style="position: relative; left: -1.5rem;">
			<li>
				<a href="{% url 'phdc_app:student_profile_nav' %}" class="btn"> 
					<i class="ri-user-line" id="homea-controlp-icon"></i>&nbsp;<span id="homea-controlp-text">Профіль</span> 
				</a>
			</li> 
			<li>
				<button hx-get="{% url 'phdc_app:send_email' %}" hx-target="#dialog" data-bs-backdrop="static" class="btn">
					<i class="ri-chat-3-line" id="homea-msg-icon"></i>&nbsp;<span id="homea-msg-text">Повідомлення</span>
				</button>
			</li>
			<li>
				<a href="{% url 'phdc_app:deadlines' %}" class="btn">
					<i class="ri-timer-line" id="homea-deadline-icon"></i>&nbsp;<span id="homea-deadline-text">Дедлайни</span> 
				</a>
			</li>
			<li>
				<a href="{% url 'phdc_app:seminars' %}" class="btn"> 
					<i class="ri-presentation-line" id="homea-controlp-icon"></i>&nbsp;<span id="homea-controlp-text">Семінари</span> 
				</a>
			</li> 
		</ul>
		{% endif %}
	</div>

	<div class="homea-nav-btns" {% if group == 'phdstudents' %} style="position: relative; left: 21rem;" {% else %} style="position: relative; right: 2rem;" {% endif %}>
			{% if group != 'phdstudents' %}
			<div class="homea-nav-notif-btn">
				<button hx-get="{% url 'phdc_app:show_notifications' %}" style="border-color: transparent; background-color: #ffffff;" hx-target="#dialog" data-bs-backdrop="static"><i class="ri-notification-4-line"></i></button>
			</div>
			<div class="homea-nav-notif-btn">
				<button hx-get="{% url 'phdc_app:registration_status_toggle' %}" style="border-color: transparent; background-color: #ffffff;" hx-target="#dialog" data-bs-backdrop="static"> <i class="ri-lock-line"></i></button>
			</div>
			{% endif %}

			{% if group == 'phdstudents' %}
			<div class="homea-nav-notif-btn">
				<button hx-get="{% url 'phdc_app:show_student_notifications' %}" style="border-color: transparent; background-color: #ffffff;" hx-target="#dialog" data-bs-backdrop="static"><i class="ri-notification-4-line"></i></button>
			</div>
			{% endif %}
		
		<div class="homea-nav-search-btn">
			<div class="homea-nav-search-toggle">
				<i class="ri-close-line close"></i>
			    <i class="ri-search-2-line search"></i>
			</div>

			<form class="d-flex homea-nav-search-field">
				{% csrf_token %}
				{% block homea-search-field-input %}
				<input type="text" placeholder="Пошук">
				{% endblock homea-search-field-input %}
				<button class="btn" type="submit"><i class="ri-search-2-line"></i></button>
			</form>
		</div>
		<div class="homea-nav-reset-btn">
			{% block homea-reset-btn %}
			<i class="ri-restart-line"></i>
			{% endblock homea-reset-btn %}
		</div>
		<div class="homea-nav-logout-btn">
			<button type="button" style="border-color: transparent; background-color: #ffffff;" data-bs-toggle="modal" data-bs-target="#logout-modal"><i class="ri-logout-circle-r-line"></i></button>
		</div> 
	</div>
</div>
{% endblock base-nav-content %}

{% block base-content %}
<div class="container-fluid" id="{% block homea-main-container %}homea-main-container{% endblock homea-main-container %}">
	<div class="container"> 
		<div class="homea-sections-panel">
			<div class="homea-section">
				<h1 class="{% block homea-title %} homea-title {% endblock homea-title %}">{% block homea-section-title %}<i class="ri-tools-line"></i>&nbsp;Панель керування {% endblock homea-section-title %}</h1>
				<div class="{% block homea-cards-list %} homea-cards-list {% endblock homea-cards-list %}">
					{% block homea-cards-list-content %}
					{% if group != 'phdstudents' %}
					<div class="homea-card">
						<i class="ri-graduation-cap-line"></i>
						<h2>Аспіранти</h2>
						<p>Перегляньте список аспірантів, зареєстрованих в системі.</p>
						<hr>
						<a href="{% url 'phdc_app:students' %}" class="btn homea-go-btn">Перейти<i class="ri-arrow-right-double-line"></i></a>
					</div>
					{% endif %}
					<div class="homea-card">
						<i class="ri-glasses-line"></i>
						<h2>Викладачі</h2>
						<p>Перегляньте та налаштуйте список викладачів.</p>
						<hr>
						<a href="{% url 'phdc_app:teachers' %}" class="btn homea-go-btn">Перейти<i class="ri-arrow-right-double-line"></i></a>
					</div>
					{% if group != 'phdstudents' %}
					<div class="homea-card">
						<i class="ri-group-line"></i>
						<h2>Навчальні групи</h2>
						<p>Перегляньте список груп, в яких навчаються аспіранти.</p>
						<hr>
						<a href="{% url 'phdc_app:study_groups' %}" class="btn homea-go-btn">Перейти<i class="ri-arrow-right-double-line"></i></a>
					</div>
					{% endif %}
					{% if group != 'phdstudents' %}
					<div class="homea-card">
						<i class="ri-hammer-line"></i>
						<h2>Спеціальності</h2>
						<p>Перегляньте та налаштуйте список спеціальностей.</p>
						<hr>
						<a href="{% url 'phdc_app:specialties' %}" class="btn homea-go-btn">Перейти<i class="ri-arrow-right-double-line"></i></a>
					</div>
					{% endif %}
					<div class="homea-card">
						<i class="ri-pages-line"></i>
						<h2>Видання</h2>
						<p>Перегляньте та налаштуйте список видань.</p>
						<hr>
						<a href="{% url 'phdc_app:editions' %}" class="btn homea-go-btn">Перейти<i class="ri-arrow-right-double-line"></i></a>
					</div>
					<div class="homea-card">
						<i class="ri-shapes-line"></i>
						<h2>Типи публікацій</h2>
						<p>Перегляньте та налаштуйте типи публікацій аспірантів.</p>
						<hr>
						<a href="{% url 'phdc_app:pub_types' %}" class="btn homea-go-btn">Перейти<i class="ri-arrow-right-double-line"></i></a>
					</div>
					{% if group != 'phdstudents' %}
					<div class="homea-card">
						<i class="ri-school-line"></i>
						<h2>Кафедри</h2>
						<p>Перегляньте та налаштуйте список кафедр факультету.</p>
						<hr>
						<a href="{% url 'phdc_app:departments' %}" class="btn homea-go-btn">Перейти<i class="ri-arrow-right-double-line"></i></a>
					</div>
					{% endif %}
					<div class="homea-card">
						<i class="ri-presentation-line"></i>
						<h2>Семінари</h2>
						<p>Перегляньте та налаштуйте актуальні семінари кафедр, а також їх учасників.</p>
						<hr>
						<a href="{% url 'phdc_app:seminars' %}" class="btn homea-go-btn">Перейти<i class="ri-arrow-right-double-line"></i></a>
					</div>
				</div>
				{% endblock homea-cards-list-content %}
			</div>
		</div>
	</div>
</div>
{% endblock base-content %}

phdc_app/templates/pub_type_list.html
{% for data in pub_types %}
<tr>
  <td>{{ data.name }}</td>
  <td class="s-table-btns">
    <button hx-get="{% url 'phdc_app:delete_pub_type' id=data.id %}" hx-target="#dialog" data-bs-backdrop="static" class="btn btn-outline-secondary btn-sm text-light" id="table-delete-btn">
      <i class="ri-delete-bin-line"></i>
  </button>
  </td>
  {% empty %}
  <td colspan="6" class="s-table-empty-rcrd"><strong>Записи відсутні</strong></td>
</tr>
{% endfor %}

phdc_app/templates/pub_types.html
{% extends 'students.html' %}


{% block base-title %} PHDCENTRE: Типи публікацій {% endblock base-title %}

{% block homea-reset-btn %}
<a href="{% url 'phdc_app:pub_types' %}">
  <i class="ri-restart-line"></i>
</a>
{% endblock homea-reset-btn %}

{% block homea-search-field-input %}
<input class="form-control" type="text" name="pub_types_q" placeholder="Пошук" 
       hx-get="{% url 'phdc_app:pub_type_list' %}" 
       hx-trigger="keyup changed delay:500ms"
       hx-target="#pub_type-list">
{% endblock homea-search-field-input %}

{% block homea-section-title %} <i class="ri-shapes-line"></i>&nbsp;Типи публікацій {% endblock homea-section-title %}

{% block s-table-add-btn %}
<div class="table-add-btn" id="pbt-add-btn" style="position: relative; top: -1%; left: 6%;">
  <button hx-get="{% url 'phdc_app:add_pub_type' %}" hx-target="#dialog" data-bs-backdrop="static" class="btn btn-outline-secondary main-btn add-btn">
    <i class="ri-add-circle-line"></i> Створити тип
  </button>
</div>
{% endblock s-table-add-btn %}

{% block filters %}{% endblock filters %}

{% block s-table %}
<table id="spec-table">
{% endblock s-table %}

{% block s-table-title-col %}
<tr>
  <th>Тип</th>
  <th colspan="2">Дія</th>
</tr>
{% endblock s-table-title-col %}

{% block s-table-data-col %}
<tbody id="pub_type-list" hx-trigger="load, pubTypeUpdate from:body" hx-get="{% url 'phdc_app:pub_type_list' %}" hx-target="this">
    {% include 'pub_type_list.html' %}
</tbody>
{% endblock s-table-data-col %}